### GET request to health server
GET http://localhost:8080/api/health
Accept: application/json

### POST request to create a mission control
POST http://localhost:8080/api/mission-control
Content-Type: application/json
Accept: application/json

{
  "username": "test_user",
  "platform": {
    "width": 10,
    "height": 10
  },
  "rovers": {
    "amount": 2
  }
}

### POST request to create a mission control
GET http://localhost:8080/api/mission-control/test_user
Content-Type: application/json
Accept: application/json


### POST request to move the rovers by username
POST http://localhost:8080/api/mission-control/test_user/move-rovers
Accept: application/json

{
  "rovers": [
    {
      "uuid": "rover-uuid-1",
      "commands": "LMLMLMLMM"
    },
    {
      "uuid": "rover-uuid-2",
      "commands": "MMRMMRMRRM"
    }
  ]
}
