### GET request to health server
GET http://localhost:8080/api/health
Accept: application/json

### POST request to create a mission control
POST http://localhost:8080/api/mission-control
Content-Type: application/json
Accept: application/json

{
  "username": "test_user",
  "platform": {
    "width": 10,
    "height": 10
  },
  "rovers": {
    "amount": 3
  }
}

### GET request to get mission control by username
GET http://localhost:8080/api/mission-control/test_user
Accept: application/json
